name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  BUCKET_NAME: "hello-world"
  AWS_REGION: "us-east-2"
  GITHUB_REF: "main"

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract commit hash
        shell: bash
        run: echo "##[set-output name=commit_hash;]$(echo "$GITHUB_SHA")"
        id: extract_hash

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      # Copy build directory to S3
      - name: Copy build to S3
        run: |
          zip -r hello-world.zip . -x node_modules\* dist\* .git\*
          aws s3 cp hello-world.zip s3://deployment--buyfirm-main-service/dev/hello-world.zip

  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Deploying branch"
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          aws-region: ${{ env.AWS_REGION }}
      - run: |
          aws deploy create-deployment --application-name buyfirm-main-service --deployment-group-name dev --s3-location bucket=deployment--buyfirm-main-service,key=dev/hello-world.zip,bundleType=zip
